# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hw_grpc/course_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hw_grpc/course_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"hw_grpc/course_service.proto\x12\rcourseservice\"%\n\x10GetCourseRequest\x12\x11\n\tcourse_id\x18\x01 \x01(\t\"J\n\x11GetCourseResponse\x12\x11\n\tcourse_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t2_\n\rCourseService\x12N\n\tGetCourse\x12\x1f.courseservice.GetCourseRequest\x1a .courseservice.GetCourseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hw_grpc.course_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCOURSEREQUEST']._serialized_start=53
  _globals['_GETCOURSEREQUEST']._serialized_end=90
  _globals['_GETCOURSERESPONSE']._serialized_start=92
  _globals['_GETCOURSERESPONSE']._serialized_end=166
  _globals['_COURSESERVICE']._serialized_start=168
  _globals['_COURSESERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
